### ISSUE TITLE
Over-identifying hidden information on a webpage

### ISSUE THREAD

**Issue by YokiiW** [jasonthewhale/CS_Hackathon_Capybara#3]
As titled, the following is just an example I encountered during my browsing process; I am unsure whether other webpages may have similar issues.
<img width="1426" alt="Screen Shot 2023-09-30 at 15 47 40" src="https://github.com/jasonthewhale/CS_Hackathon_Capybara/assets/131126378/03ad18be-0c6b-4a26-9d7d-b3377fa7bb9c">

**Comment by Alaurant** [comment]
Same question
![hidden info](https://github.com/jasonthewhale/CS_Hackathon_Capybara/assets/41817560/95501dbf-39d0-41d2-9f3b-4946a4c2467f)

**Comment by jasonthewhale** [comment]
Woah, that's massive false positive. Thx for pointing out. 

Seems the structure of these websites contains multiple overlaied invinsible elements, while previous color similarity logic checked two adjacent elements and report crazy amount of hidden information.

Fixed by adding visibility condition.

<div align="center">
<img width="600" alt="Screenshot 2023-10-01 at 11 01 31 am" src="https://github.com/jasonthewhale/CS_Hackathon_Capybara/assets/80374292/19cf0e5b-96c0-4fcd-a0f9-5c56302c3b74">

<img width="600" alt="Screenshot 2023-10-01 at 11 01 45 am" src="https://github.com/jasonthewhale/CS_Hackathon_Capybara/assets/80374292/b9a92ed8-50ab-4611-8939-7959519af457">
</div>
